name: Dependency Review

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Dependency Review
        uses: actions/dependency-review-action@da24556a548c5e4b45e7eb7bc8a8e4e3e8d3ccd2 # v4.7.1
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: always
