name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.4.1
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v5.1.0
        with:
          python-version: 3.x
      - run: python3 -m pip install --require-hashes -r scripts/requirements-docs.txt
      - run: mkdocs gh-deploy --force